
export const UI_TEXT = {
  APP_NAME: "Merendola Calendar",
  SIGN_IN: {
    TITLE: "Bienvenido a Merendola Calendar",
    SUBTITLE: "El punto de encuentro para los descansos de tu equipo",
    EMAIL: "Correo electrónico personal",
    PASSWORD: "Contraseña",
    CONTINUE: "Iniciar sesión",
    HELP: "Soporte técnico",
    NO_ACCOUNT: "¿Nuevo en el equipo? Crea una cuenta gratis",
    FORGOT: "¿Has olvidado tu contraseña?",
  },
  TEAM_SETUP: {
    TITLE: "Prepara tu equipo",
    SUBTITLE: "Organiza las meriendas y cumpleaños con tus compañeros.",
    CREATE_TAB: "Crear un nuevo equipo",
    JOIN_TAB: "Unirse con un código",
    TEAM_NAME: "Nombre del equipo (ej: Desarrollo, Marketing...)",
    INVITE_CODE: "Código de invitación",
    CREATE_BTN: "Crear equipo y continuar",
    JOIN_BTN: "Acceder al equipo",
    AVAILABLE: "¡Ese nombre está libre!",
  },
  PROFILE: {
    TITLE: "Tu perfil",
    REQUIRED_ACTION: "Acción pendiente",
    NAME: "Tu nombre completo",
    BIRTHDAY: "Fecha de nacimiento (DD/MM/AAAA) *",
    SAVE: "Guardar cambios",
    BLOCK_MSG: "Dinos cuándo es tu cumple y tu email para avisarte",
    LOGOUT: "Cerrar sesión de forma segura",
    SUCCESS_MSG: "¡Perfil actualizado con éxito!",
    EMAIL_LABEL: "Correo electrónico personal",
    EMAIL_ERROR: "Introduce un email válido para continuar",
  },
  DASHBOARD: {
    NOTIFICATIONS: {
      TITLE: "Centro de Avisos",
      EMPTY: "No tienes avisos pendientes",
      INVITE_TOAST: "Nueva invitación",
      INVITE_MSG: (name: string) => `${name} te ha invitado a una merendola`,
      ACCEPT: "Asistiré",
      REJECT: "No puedo",
    },
    ATTENDEES: {
      TITLE: "Lista de asistencia",
      YES: "Asisten",
      NO: "No asisten",
      PENDING: "Pendientes",
    },
    CONFLICT: "Se han detectado planes simultáneos.",
    RESOLVE: "Ver conflictos",
    ADD_SNACK: "Organizar encuentro",
    NEXT_SNACKS: "Próximas citas",
    EMPTY_SNACKS: "¿Quién organiza la primera merienda?",
    MANAGE_TITLE: "Detalles del Encuentro",
    DATE: "Día",
    TIME: "Hora",
    EVENT_TITLE: "Nombre del encuentro",
    CONTRIBUTION: "¿Qué vas a traer tú?",
    CANCEL: "Cancelar",
    SAVE: "Confirmar",
    DELETE: "Eliminar",
    SUCCESS_MSG: "¡Encuentro programado!",
    ATTENDANCE: {
      JOIN: "¡Me apunto!",
      LEAVE: "Ya no puedo ir",
      COUNT: "asistentes",
    },
    COMMENTS: {
      TITLE: "Conversación",
      PLACEHOLDER: "Añade un comentario o duda...",
      SEND: "Enviar"
    },
    CALENDAR_EXPORT: "Añadir a mi calendario (.ics)"
  },
  COMMON: {
    LOADING: "Cargando...",
    ERROR: "Error inesperado.",
    CONFIRM_DELETE: "¿Seguro que quieres eliminar esta merendola?",
    DELETE_VERIFICATION: "Escribe ELIMINAR para confirmar",
  }
};
